name: Build Package
on:
  workflow_call:
    inputs:
      package_short_name:
        type: string
        required: true
      version:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.4
          run_install: |
            - args: [--no-frozen-lockfile]

      - name: 设置版本
        if: ${{ inputs.version }}
        run: pnpm set version ${{ inputs.version }}
        
      - name: 构建
        run: |
          pnpm build
          pnpm pkg delete devDependencies
          mkdir -p ${{ runner.temp }}/temp/
          cp -r package.json CHANGELOG.md README.md LICENSE resources config lib ${{ runner.temp }}/temp/

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package_short_name }}
          path: ${{ runner.temp }}/temp/